/* polyspace<MISRA-C:19.15:Not a defect:Justify with annotations> No Impact of this rule violation (AUTOSAR Standard : Memory Mapping) */

/*******************************************************************************
**  FILE-NAME: Rte_MemMap.h                                                     **
**                                                                            **
**  MODULE-NAME: AUTOSAR RTE GENERATION TOOL                                  **
**                                                                            **
**  NOTE: This file is auto generated, do not edit this file manually.        **
**                                                                            **
********************************************************************************

********************************************************************************
**                      Generation Tool Information                           **
********************************************************************************
**  Tool Version: 4.4.2                                                   **
**                                                                            **
**  Change History: Refer log file (use -l option to generate log file)       **
**                                                                            **
********************************************************************************
**                      File Generation Information                           **
*******************************************************************************/
/*
 * INPUT FILE:
 *      D:\xar_svn\Education_201803\autron_autosar_edu_for_MPC5606B_Base\Configuration\ECU\ECUCD_EcucValueCollection.arxml
 *      D:\xar_svn\Education_201803\autron_autosar_edu_for_MPC5606B_Base\Configuration\ECU\Ecud_Cal.arxml
 *      D:\xar_svn\Education_201803\autron_autosar_edu_for_MPC5606B_Base\Configuration\ECU\Ecud_Com.arxml
 *      D:\xar_svn\Education_201803\autron_autosar_edu_for_MPC5606B_Base\Configuration\ECU\Ecud_Det.arxml
 *      D:\xar_svn\Education_201803\autron_autosar_edu_for_MPC5606B_Base\Configuration\ECU\Ecud_EcuC.arxml
 *      D:\xar_svn\Education_201803\autron_autosar_edu_for_MPC5606B_Base\Configuration\ECU\Ecud_Os.arxml
 *      D:\xar_svn\Education_201803\autron_autosar_edu_for_MPC5606B_Base\Configuration\ECU\Ecud_Rte.arxml
 *      D:\xar_svn\Education_201803\autron_autosar_edu_for_MPC5606B_Base\Configuration\System\BswMd\Bswmd_Adc.arxml
 *      D:\xar_svn\Education_201803\autron_autosar_edu_for_MPC5606B_Base\Configuration\System\BswMd\Bswmd_BswM.arxml
 *      D:\xar_svn\Education_201803\autron_autosar_edu_for_MPC5606B_Base\Configuration\System\BswMd\Bswmd_Can.arxml
 *      D:\xar_svn\Education_201803\autron_autosar_edu_for_MPC5606B_Base\Configuration\System\BswMd\Bswmd_CanIf.arxml
 *      D:\xar_svn\Education_201803\autron_autosar_edu_for_MPC5606B_Base\Configuration\System\BswMd\Bswmd_CanSM.arxml
 *      D:\xar_svn\Education_201803\autron_autosar_edu_for_MPC5606B_Base\Configuration\System\BswMd\Bswmd_CanTp.arxml
 *      D:\xar_svn\Education_201803\autron_autosar_edu_for_MPC5606B_Base\Configuration\System\BswMd\Bswmd_Com.arxml
 *      D:\xar_svn\Education_201803\autron_autosar_edu_for_MPC5606B_Base\Configuration\System\BswMd\Bswmd_ComM.arxml
 *      D:\xar_svn\Education_201803\autron_autosar_edu_for_MPC5606B_Base\Configuration\System\BswMd\Bswmd_Crc.arxml
 *      D:\xar_svn\Education_201803\autron_autosar_edu_for_MPC5606B_Base\Configuration\System\BswMd\Bswmd_Dcm.arxml
 *      D:\xar_svn\Education_201803\autron_autosar_edu_for_MPC5606B_Base\Configuration\System\BswMd\Bswmd_Dem.arxml
 *      D:\xar_svn\Education_201803\autron_autosar_edu_for_MPC5606B_Base\Configuration\System\BswMd\Bswmd_Det.arxml
 *      D:\xar_svn\Education_201803\autron_autosar_edu_for_MPC5606B_Base\Configuration\System\BswMd\Bswmd_Dio.arxml
 *      D:\xar_svn\Education_201803\autron_autosar_edu_for_MPC5606B_Base\Configuration\System\BswMd\Bswmd_Fee.arxml
 *      D:\xar_svn\Education_201803\autron_autosar_edu_for_MPC5606B_Base\Configuration\System\BswMd\Bswmd_FiM.arxml
 *      D:\xar_svn\Education_201803\autron_autosar_edu_for_MPC5606B_Base\Configuration\System\BswMd\Bswmd_Fls.arxml
 *      D:\xar_svn\Education_201803\autron_autosar_edu_for_MPC5606B_Base\Configuration\System\BswMd\Bswmd_Gpt.arxml
 *      D:\xar_svn\Education_201803\autron_autosar_edu_for_MPC5606B_Base\Configuration\System\BswMd\Bswmd_Icu_43.arxml
 *      D:\xar_svn\Education_201803\autron_autosar_edu_for_MPC5606B_Base\Configuration\System\BswMd\Bswmd_Mcu.arxml
 *      D:\xar_svn\Education_201803\autron_autosar_edu_for_MPC5606B_Base\Configuration\System\BswMd\Bswmd_MemIf.arxml
 *      D:\xar_svn\Education_201803\autron_autosar_edu_for_MPC5606B_Base\Configuration\System\BswMd\Bswmd_NvM.arxml
 *      D:\xar_svn\Education_201803\autron_autosar_edu_for_MPC5606B_Base\Configuration\System\BswMd\Bswmd_Os.arxml
 *      D:\xar_svn\Education_201803\autron_autosar_edu_for_MPC5606B_Base\Configuration\System\BswMd\Bswmd_PduR.arxml
 *      D:\xar_svn\Education_201803\autron_autosar_edu_for_MPC5606B_Base\Configuration\System\BswMd\Bswmd_Port.arxml
 *      D:\xar_svn\Education_201803\autron_autosar_edu_for_MPC5606B_Base\Configuration\System\BswMd\Bswmd_Pwm_43.arxml
 *      D:\xar_svn\Education_201803\autron_autosar_edu_for_MPC5606B_Base\Configuration\System\BswMd\Bswmd_Spi.arxml
 *      D:\xar_svn\Education_201803\autron_autosar_edu_for_MPC5606B_Base\Configuration\System\BswMd\Bswmd_Wdg_43.arxml
 *      D:\xar_svn\Education_201803\autron_autosar_edu_for_MPC5606B_Base\Configuration\System\Composition\EcuExtract.arxml
 *      D:\xar_svn\Education_201803\autron_autosar_edu_for_MPC5606B_Base\Configuration\System\DBImport\Project.arxml
 *      D:\xar_svn\Education_201803\autron_autosar_edu_for_MPC5606B_Base\Configuration\System\DataTypes\AUTOSAR_DataTypes.arxml
 *      D:\xar_svn\Education_201803\autron_autosar_edu_for_MPC5606B_Base\Configuration\System\DataTypes\AUTOSAR_DataTypes_Etc.arxml
 *      D:\xar_svn\Education_201803\autron_autosar_edu_for_MPC5606B_Base\Configuration\System\Swcd_App\App_ComM.arxml
 *      D:\xar_svn\Education_201803\autron_autosar_edu_for_MPC5606B_Base\Configuration\System\Swcd_App\App_Dcm.arxml
 *      D:\xar_svn\Education_201803\autron_autosar_edu_for_MPC5606B_Base\Configuration\System\Swcd_App\App_Dem.arxml
 *      D:\xar_svn\Education_201803\autron_autosar_edu_for_MPC5606B_Base\Configuration\System\Swcd_App\App_FiM.arxml
 *      D:\xar_svn\Education_201803\autron_autosar_edu_for_MPC5606B_Base\Configuration\System\Swcd_App\App_Mode.arxml
 *      D:\xar_svn\Education_201803\autron_autosar_edu_for_MPC5606B_Base\Configuration\System\Swcd_App\App_WdgM.arxml
 *      D:\xar_svn\Education_201803\autron_autosar_edu_for_MPC5606B_Base\Configuration\System\Swcd_Bsw\MODE_PortInterfaces.arxml
 *      D:\xar_svn\Education_201803\autron_autosar_edu_for_MPC5606B_Base\Configuration\System\Swcd_Bsw\Swcd_Bsw_BswM.arxml
 *      D:\xar_svn\Education_201803\autron_autosar_edu_for_MPC5606B_Base\Configuration\System\Swcd_Bsw\Swcd_ComM.arxml
 *      D:\xar_svn\Education_201803\autron_autosar_edu_for_MPC5606B_Base\Configuration\System\Swcd_Bsw\Swcd_Det.arxml
 *      D:\xar_svn\Education_201803\autron_autosar_edu_for_MPC5606B_Base\Configuration\System\Swcd_Bsw\Swcd_FiM.arxml
 *      D:\xar_svn\Education_201803\autron_autosar_edu_for_MPC5606B_Base\Generated\Bsw_Output\bswmd\Bswmd_Cal.arxml
 *      D:\xar_svn\Education_201803\autron_autosar_edu_for_MPC5606B_Base\Generated\Bsw_Output\bswmd\Bswmd_EcuM.arxml
 *      D:\xar_svn\Education_201803\autron_autosar_edu_for_MPC5606B_Base\Generated\Bsw_Output\bswmd\Bswmd_IoHwAb.arxml
 *      D:\xar_svn\Education_201803\autron_autosar_edu_for_MPC5606B_Base\Generated\Bsw_Output\bswmd\Bswmd_WdgIf.arxml
 *      D:\xar_svn\Education_201803\autron_autosar_edu_for_MPC5606B_Base\Generated\Bsw_Output\bswmd\Bswmd_WdgM.arxml
 *      D:\xar_svn\Education_201803\autron_autosar_edu_for_MPC5606B_Base\Generated\Bsw_Output\swcd\Swcd_Bsw_Dcm.arxml
 *      D:\xar_svn\Education_201803\autron_autosar_edu_for_MPC5606B_Base\Generated\Bsw_Output\swcd\Swcd_Bsw_Dem.arxml
 *      D:\xar_svn\Education_201803\autron_autosar_edu_for_MPC5606B_Base\Generated\Bsw_Output\swcd\Swcd_Bsw_EcuM.arxml
 *      D:\xar_svn\Education_201803\autron_autosar_edu_for_MPC5606B_Base\Generated\Bsw_Output\swcd\Swcd_Bsw_NvM.arxml
 *      D:\xar_svn\Education_201803\autron_autosar_edu_for_MPC5606B_Base\Generated\Bsw_Output\swcd\Swcd_IoHwAb.arxml
 *      D:\xar_svn\Education_201803\autron_autosar_edu_for_MPC5606B_Base\Generated\Bsw_Output\swcd\Swcd_WdgM.arxml
 *      D:\xar_svn\Education_201803\autron_autosar_edu_for_MPC5606B_Base\Static_Code\Modules\b_autosar_swc_ErrorManagement\App_ErrM.arxml
 *      D:\xar_svn\Education_201803\autron_autosar_edu_for_MPC5606B_Base\Static_Code\Modules\b_autosar_sys_EcuM_R40\generator\EcuM_PortInterface.arxml
 *      D:\xar_svn\Education_201803\autron_autosar_edu_for_MPC5606B_Base\Static_Code\Modules\b_autosar_sys_WdgM_R40\generator\Swcd_WdgM_Fixed.arxml

 * GENERATED ON:  This timestamp is removed.
*/

/*******************************************************************************
* PRE-JUSTIFICATION BEGINE SECTION (MISRA-C RULE CHECKER)
* These rules will not be applied for verification based on the MISRA Rule
* in Rte generated source
*******************************************************************************/
/*
  polyspace:begin<MISRA-C:19.1:Not a defect:Justify with annotations> No Impact of this rule violation (AUTOSAR Standard : Memory Mapping)
  polyspace:begin<MISRA-C:19.4:Not a defect:Justify with annotations> No Impact of this rule violation (AUTOSAR Standard : Rte SWS #1154, #6713)
  polyspace:begin<MISRA-C:19.6:Not a defect:Justify with annotations> No Impact of this rule violation (AUTOSAR Standard : Memory Mapping)
  polyspace:begin<MISRA-C:19.7:Not a defect:Justify with annotations> No Impact of this rule violation (AUTOSAR Standard : Rte SWS #1236)
*/

/******************************************************************************/

/*******************************************************************************
**                         MULTIPLE INCLUSION PROTECTION                      **
*******************************************************************************/
#ifndef NO_RTE_MEMMAP_INCLUSITON

/*******************************************************************************
**                         Version Information                                **
*******************************************************************************/
#ifdef RTE_VENDOR_ID
  #if (RTE_VENDOR_ID != 76)
    #error "Rte_Cfg.h : Mismatch in Rte Specification Vendor Id"
  #endif
#else
  #define RTE_VENDOR_ID 76
#endif

#ifdef RTE_MODULE_ID
  #if (RTE_MODULE_ID != 2)
    #error "Rte_Cfg.h : Mismatch in Rte Specification Module Id"
  #endif
#else
  #define RTE_MODULE_ID 2
#endif

#ifdef RTE_SW_MAJOR_VERSION
  #if (RTE_SW_MAJOR_VERSION != 4)
    #error "Rte_Cfg.h : Mismatch in Rte Specification Major Version"
  #endif
#else
  #define RTE_SW_MAJOR_VERSION 4
#endif

#ifdef RTE_SW_MINOR_VERSION
  #if (RTE_SW_MINOR_VERSION != 4)
    #error "Rte_Cfg.h : Mismatch in Rte Specification Minor Version"
  #endif
#else
  #define RTE_SW_MINOR_VERSION 4
#endif

#ifdef RTE_SW_PATCH_VERSION
  #if (RTE_SW_PATCH_VERSION != 2)
    #error "Rte_Cfg.h : Mismatch in Rte Specification Patch Version"
  #endif
#else
  #define RTE_SW_PATCH_VERSION 2
#endif

#ifdef RTE_AR_RELEASE_MAJOR_VERSION
  #if (RTE_AR_RELEASE_MAJOR_VERSION != 4)
    #error "Rte_Cfg.h : Mismatch in Rte Specification Release Major Version"
  #endif
#else
  #define RTE_AR_RELEASE_MAJOR_VERSION 4
#endif

#ifdef RTE_AR_RELEASE_MINOR_VERSION
  #if (RTE_AR_RELEASE_MINOR_VERSION != 0)
    #error "Rte_Cfg.h : Mismatch in Rte Specification Release Minor Version"
  #endif
#else
  #define RTE_AR_RELEASE_MINOR_VERSION 0
#endif

#ifdef RTE_AR_RELEASE_REVISION_VERSION
  #if (RTE_AR_RELEASE_REVISION_VERSION != 3)
    #error "Rte_Cfg.h : Mismatch in Rte Specification Release Revision Version"
  #endif
#else
  #define RTE_AR_RELEASE_REVISION_VERSION 3
#endif

/*******************************************************************************
**                         Memory Map Protection                              **
*******************************************************************************/
#if defined (START_WITH_IF)
#elif defined (RTE_START_SEC_VAR_BOOLEAN)
  #undef RTE_START_SEC_VAR_BOOLEAN
  
//  #pragma ghs section bss=".bss.DEFAULT_RAM_VAR_CLEARED"
//  #pragma ghs section data=".data.DEFAULT_RAM_VAR_INIT"

#elif defined (RTE_STOP_SEC_VAR_BOOLEAN)
  #undef RTE_STOP_SEC_VAR_BOOLEAN
  
//  #pragma ghs section data=default
//  #pragma ghs section bss=default

#elif defined (RTE_START_SEC_VAR_8)
  #undef RTE_START_SEC_VAR_8
  
//  #pragma ghs section bss=".bss.DEFAULT_RAM_VAR_CLEARED"
//  #pragma ghs section data=".data.DEFAULT_RAM_VAR_INIT"

#elif defined (RTE_STOP_SEC_VAR_8)
  #undef RTE_STOP_SEC_VAR_8
  
//  #pragma ghs section data=default
//  #pragma ghs section bss=default

#elif defined (RTE_START_SEC_VAR_16)
  #undef RTE_START_SEC_VAR_16
  
//  #pragma ghs section bss=".bss.DEFAULT_RAM_VAR_CLEARED"
//  #pragma ghs section data=".data.DEFAULT_RAM_VAR_INIT"

#elif defined (RTE_STOP_SEC_VAR_16)
  #undef RTE_STOP_SEC_VAR_16
  
//  #pragma ghs section data=default
//  #pragma ghs section bss=default

#elif defined (RTE_START_SEC_VAR_32)
  #undef RTE_START_SEC_VAR_32
  
//  #pragma ghs section bss=".bss.DEFAULT_RAM_VAR_CLEARED"
//  #pragma ghs section data=".data.DEFAULT_RAM_VAR_INIT"

#elif defined (RTE_STOP_SEC_VAR_32)
  #undef RTE_STOP_SEC_VAR_32
  
//  #pragma ghs section data=default
//  #pragma ghs section bss=default

#elif defined (RTE_START_SEC_VAR_UNSPECIFIED)
  #undef RTE_START_SEC_VAR_UNSPECIFIED
  
//  #pragma ghs section bss=".bss.DEFAULT_RAM_VAR_CLEARED"
//  #pragma ghs section data=".data.DEFAULT_RAM_VAR_INIT"

#elif defined (RTE_STOP_SEC_VAR_UNSPECIFIED)
  #undef RTE_STOP_SEC_VAR_UNSPECIFIED
  
//  #pragma ghs section data=default
//  #pragma ghs section bss=default

#elif defined (RTE_START_SEC_VAR_NO_INIT_BOOLEAN)
  #undef RTE_START_SEC_VAR_NO_INIT_BOOLEAN
  
//  #pragma ghs section bss=".bss.DEFAULT_RAM_VAR_NO_INIT"

#elif defined (RTE_STOP_SEC_VAR_NO_INIT_BOOLEAN)
  #undef RTE_STOP_SEC_VAR_NO_INIT_BOOLEAN
  
//  #pragma ghs section bss=default

#elif defined (RTE_START_SEC_VAR_NO_INIT_8)
  #undef RTE_START_SEC_VAR_NO_INIT_8
  
//  #pragma ghs section bss=".bss.DEFAULT_RAM_VAR_NO_INIT"

#elif defined (RTE_STOP_SEC_VAR_NO_INIT_8)
  #undef RTE_STOP_SEC_VAR_NO_INIT_8
  
//  #pragma ghs section bss=default

#elif defined (RTE_START_SEC_VAR_NO_INIT_16)
  #undef RTE_START_SEC_VAR_NO_INIT_16
  
//  #pragma ghs section bss=".bss.DEFAULT_RAM_VAR_NO_INIT"

#elif defined (RTE_STOP_SEC_VAR_NO_INIT_16)
  #undef RTE_STOP_SEC_VAR_NO_INIT_16
  
//  #pragma ghs section bss=default

#elif defined (RTE_START_SEC_VAR_NO_INIT_32)
  #undef RTE_START_SEC_VAR_NO_INIT_32
  
//  #pragma ghs section bss=".bss.DEFAULT_RAM_VAR_NO_INIT"

#elif defined (RTE_STOP_SEC_VAR_NO_INIT_32)
  #undef RTE_STOP_SEC_VAR_NO_INIT_32
  
//  #pragma ghs section bss=default

#elif defined (RTE_START_SEC_VAR_NO_INIT_UNSPECIFIED)
  #undef RTE_START_SEC_VAR_NO_INIT_UNSPECIFIED
  
//  #pragma ghs section bss=".bss.DEFAULT_RAM_VAR_NO_INIT"

#elif defined (RTE_STOP_SEC_VAR_NO_INIT_UNSPECIFIED)
  #undef RTE_STOP_SEC_VAR_NO_INIT_UNSPECIFIED
  
//  #pragma ghs section bss=default

#elif defined (RTE_START_SEC_VAR_CLEARED_BOOLEAN)
  #undef RTE_START_SEC_VAR_CLEARED_BOOLEAN
  
//  #pragma ghs section bss=".bss.DEFAULT_RAM_VAR_CLEARED"

#elif defined (RTE_STOP_SEC_VAR_CLEARED_BOOLEAN)
  #undef RTE_STOP_SEC_VAR_CLEARED_BOOLEAN
  
//  #pragma ghs section bss=default

#elif defined (RTE_START_SEC_VAR_CLEARED_8)
  #undef RTE_START_SEC_VAR_CLEARED_8
  
//  #pragma ghs section bss=".bss.DEFAULT_RAM_VAR_CLEARED"

#elif defined (RTE_STOP_SEC_VAR_CLEARED_8)
  #undef RTE_STOP_SEC_VAR_CLEARED_8
  
//  #pragma ghs section bss=default

#elif defined (RTE_START_SEC_VAR_CLEARED_16)
  #undef RTE_START_SEC_VAR_CLEARED_16
  
//  #pragma ghs section bss=".bss.DEFAULT_RAM_VAR_CLEARED"

#elif defined (RTE_STOP_SEC_VAR_CLEARED_16)
  #undef RTE_STOP_SEC_VAR_CLEARED_16
  
//  #pragma ghs section bss=default

#elif defined (RTE_START_SEC_VAR_CLEARED_32)
  #undef RTE_START_SEC_VAR_CLEARED_32
  
//  #pragma ghs section bss=".bss.DEFAULT_RAM_VAR_CLEARED"

#elif defined (RTE_STOP_SEC_VAR_CLEARED_32)
  #undef RTE_STOP_SEC_VAR_CLEARED_32
  
//  #pragma ghs section bss=default

#elif defined (RTE_START_SEC_VAR_CLEARED_UNSPECIFIED)
  #undef RTE_START_SEC_VAR_CLEARED_UNSPECIFIED
  
//  #pragma ghs section bss=".bss.DEFAULT_RAM_VAR_CLEARED"

#elif defined (RTE_STOP_SEC_VAR_CLEARED_UNSPECIFIED)
  #undef RTE_STOP_SEC_VAR_CLEARED_UNSPECIFIED
  
//  #pragma ghs section bss=default

#elif defined (RTE_START_SEC_VAR_INIT_BOOLEAN)
  #undef RTE_START_SEC_VAR_INIT_BOOLEAN
  
//  #pragma ghs section data=".data.DEFAULT_RAM_VAR_INIT"

#elif defined (RTE_STOP_SEC_VAR_INIT_BOOLEAN)
  #undef RTE_STOP_SEC_VAR_INIT_BOOLEAN
  
//  #pragma ghs section data=default

#elif defined (RTE_START_SEC_VAR_INIT_8)
  #undef RTE_START_SEC_VAR_INIT_8
  
//  #pragma ghs section data=".data.DEFAULT_RAM_VAR_INIT"

#elif defined (RTE_STOP_SEC_VAR_INIT_8)
  #undef RTE_STOP_SEC_VAR_INIT_8
  
//  #pragma ghs section data=default

#elif defined (RTE_START_SEC_VAR_INIT_16)
  #undef RTE_START_SEC_VAR_INIT_16
  
//  #pragma ghs section data=".data.DEFAULT_RAM_VAR_INIT"

#elif defined (RTE_STOP_SEC_VAR_INIT_16)
  #undef RTE_STOP_SEC_VAR_INIT_16
  
//  #pragma ghs section data=default

#elif defined (RTE_START_SEC_VAR_INIT_32)
  #undef RTE_START_SEC_VAR_INIT_32
  
//  #pragma ghs section data=".data.DEFAULT_RAM_VAR_INIT"

#elif defined (RTE_STOP_SEC_VAR_INIT_32)
  #undef RTE_STOP_SEC_VAR_INIT_32
  
//  #pragma ghs section data=default

#elif defined (RTE_START_SEC_VAR_INIT_UNSPECIFIED)
  #undef RTE_START_SEC_VAR_INIT_UNSPECIFIED
  
//  #pragma ghs section data=".data.DEFAULT_RAM_VAR_INIT"

#elif defined (RTE_STOP_SEC_VAR_INIT_UNSPECIFIED)
  #undef RTE_STOP_SEC_VAR_INIT_UNSPECIFIED
  
//  #pragma ghs section data=default

#elif defined (RTE_START_SEC_VAR_POWER_ON_CLEARED_BOOLEAN)
  #undef RTE_START_SEC_VAR_POWER_ON_CLEARED_BOOLEAN
  #error "RTE does not support RTE_START_SEC_VAR_POWER_ON_CLEARED_BOOLEAN memory section"

#elif defined (RTE_STOP_SEC_VAR_POWER_ON_CLEARED_BOOLEAN)
  #undef RTE_STOP_SEC_VAR_POWER_ON_CLEARED_BOOLEAN
  #error "RTE does not support RTE_STOP_SEC_VAR_POWER_ON_CLEARED_BOOLEAN memory section"

#elif defined (RTE_START_SEC_VAR_POWER_ON_CLEARED_8)
  #undef RTE_START_SEC_VAR_POWER_ON_CLEARED_8
  #error "RTE does not support RTE_START_SEC_VAR_POWER_ON_CLEARED_8 memory section"

#elif defined (RTE_STOP_SEC_VAR_POWER_ON_CLEARED_8)
  #undef RTE_STOP_SEC_VAR_POWER_ON_CLEARED_8
  #error "RTE does not support RTE_STOP_SEC_VAR_POWER_ON_CLEARED_8 memory section"

#elif defined (RTE_START_SEC_VAR_POWER_ON_CLEARED_16)
  #undef RTE_START_SEC_VAR_POWER_ON_CLEARED_16
  #error "RTE does not support RTE_START_SEC_VAR_POWER_ON_CLEARED_16 memory section"

#elif defined (RTE_STOP_SEC_VAR_POWER_ON_CLEARED_16)
  #undef RTE_STOP_SEC_VAR_POWER_ON_CLEARED_16
  #error "RTE does not support RTE_STOP_SEC_VAR_POWER_ON_CLEARED_16 memory section"

#elif defined (RTE_START_SEC_VAR_POWER_ON_CLEARED_32)
  #undef RTE_START_SEC_VAR_POWER_ON_CLEARED_32
  #error "RTE does not support RTE_START_SEC_VAR_POWER_ON_CLEARED_32 memory section"

#elif defined (RTE_STOP_SEC_VAR_POWER_ON_CLEARED_32)
  #undef RTE_STOP_SEC_VAR_POWER_ON_CLEARED_32
  #error "RTE does not support RTE_STOP_SEC_VAR_POWER_ON_CLEARED_32 memory section"

#elif defined (RTE_START_SEC_VAR_POWER_ON_CLEARED_UNSPECIFIED)
  #undef RTE_START_SEC_VAR_POWER_ON_CLEARED_UNSPECIFIED
  #error "RTE does not support RTE_START_SEC_VAR_POWER_ON_CLEARED_UNSPECIFIED memory section"

#elif defined (RTE_STOP_SEC_VAR_POWER_ON_CLEARED_UNSPECIFIED)
  #undef RTE_STOP_SEC_VAR_POWER_ON_CLEARED_UNSPECIFIED
  #error "RTE does not support RTE_STOP_SEC_VAR_POWER_ON_CLEARED_UNSPECIFIED memory section"

#elif defined (RTE_START_SEC_VAR_POWER_ON_INIT_BOOLEAN)
  #undef RTE_START_SEC_VAR_POWER_ON_INIT_BOOLEAN
  #error "RTE does not support RTE_START_SEC_VAR_POWER_ON_INIT_BOOLEAN memory section"

#elif defined (RTE_STOP_SEC_VAR_POWER_ON_INIT_BOOLEAN)
  #undef RTE_STOP_SEC_VAR_POWER_ON_INIT_BOOLEAN
  #error "RTE does not support RTE_STOP_SEC_VAR_POWER_ON_INIT_BOOLEAN memory section"

#elif defined (RTE_START_SEC_VAR_POWER_ON_INIT_8)
  #undef RTE_START_SEC_VAR_POWER_ON_INIT_8
  #error "RTE does not support RTE_START_SEC_VAR_POWER_ON_INIT_8 memory section"

#elif defined (RTE_STOP_SEC_VAR_POWER_ON_INIT_8)
  #undef RTE_STOP_SEC_VAR_POWER_ON_INIT_8
  #error "RTE does not support RTE_STOP_SEC_VAR_POWER_ON_INIT_8 memory section"

#elif defined (RTE_START_SEC_VAR_POWER_ON_INIT_16)
  #undef RTE_START_SEC_VAR_POWER_ON_INIT_16
  #error "RTE does not support RTE_START_SEC_VAR_POWER_ON_INIT_16 memory section"

#elif defined (RTE_STOP_SEC_VAR_POWER_ON_INIT_16)
  #undef RTE_STOP_SEC_VAR_POWER_ON_INIT_16
  #error "RTE does not support RTE_STOP_SEC_VAR_POWER_ON_INIT_16 memory section"

#elif defined (RTE_START_SEC_VAR_POWER_ON_INIT_32)
  #undef RTE_START_SEC_VAR_POWER_ON_INIT_32
  #error "RTE does not support RTE_START_SEC_VAR_POWER_ON_INIT_32 memory section"

#elif defined (RTE_STOP_SEC_VAR_POWER_ON_INIT_32)
  #undef RTE_STOP_SEC_VAR_POWER_ON_INIT_32
  #error "RTE does not support RTE_STOP_SEC_VAR_POWER_ON_INIT_32 memory section"

#elif defined (RTE_START_SEC_VAR_POWER_ON_INIT_UNSPECIFIED)
  #undef RTE_START_SEC_VAR_POWER_ON_INIT_UNSPECIFIED
  #error "RTE does not support RTE_START_SEC_VAR_POWER_ON_INIT_UNSPECIFIED memory section"

#elif defined (RTE_STOP_SEC_VAR_POWER_ON_INIT_UNSPECIFIED)
  #undef RTE_STOP_SEC_VAR_POWER_ON_INIT_UNSPECIFIED
  #error "RTE does not support RTE_STOP_SEC_VAR_POWER_ON_INIT_UNSPECIFIED memory section"

#elif defined (RTE_START_SEC_VAR_FAST_BOOLEAN)
  #undef RTE_START_SEC_VAR_FAST_BOOLEAN
  #error "RTE does not support RTE_START_SEC_VAR_FAST_BOOLEAN memory section"

#elif defined (RTE_STOP_SEC_VAR_FAST_BOOLEAN)
  #undef RTE_STOP_SEC_VAR_FAST_BOOLEAN
  #error "RTE does not support RTE_STOP_SEC_VAR_FAST_BOOLEAN memory section"

#elif defined (RTE_START_SEC_VAR_FAST_8)
  #undef RTE_START_SEC_VAR_FAST_8
  #error "RTE does not support RTE_START_SEC_VAR_FAST_8 memory section"

#elif defined (RTE_STOP_SEC_VAR_FAST_8)
  #undef RTE_STOP_SEC_VAR_FAST_8
  #error "RTE does not support RTE_STOP_SEC_VAR_FAST_8 memory section"

#elif defined (RTE_START_SEC_VAR_FAST_16)
  #undef RTE_START_SEC_VAR_FAST_16
  #error "RTE does not support RTE_START_SEC_VAR_FAST_16 memory section"

#elif defined (RTE_STOP_SEC_VAR_FAST_16)
  #undef RTE_STOP_SEC_VAR_FAST_16
  #error "RTE does not support RTE_STOP_SEC_VAR_FAST_16 memory section"

#elif defined (RTE_START_SEC_VAR_FAST_32)
  #undef RTE_START_SEC_VAR_FAST_32
  #error "RTE does not support RTE_START_SEC_VAR_FAST_32 memory section"

#elif defined (RTE_STOP_SEC_VAR_FAST_32)
  #undef RTE_STOP_SEC_VAR_FAST_32
  #error "RTE does not support RTE_STOP_SEC_VAR_FAST_32 memory section"

#elif defined (RTE_START_SEC_VAR_FAST_UNSPECIFIED)
  #undef RTE_START_SEC_VAR_FAST_UNSPECIFIED
  #error "RTE does not support RTE_START_SEC_VAR_FAST_UNSPECIFIED memory section"

#elif defined (RTE_STOP_SEC_VAR_FAST_UNSPECIFIED)
  #undef RTE_STOP_SEC_VAR_FAST_UNSPECIFIED
  #error "RTE does not support RTE_STOP_SEC_VAR_FAST_UNSPECIFIED memory section"

#elif defined (RTE_START_SEC_VAR_FAST_NO_INIT_BOOLEAN)
  #undef RTE_START_SEC_VAR_FAST_NO_INIT_BOOLEAN
  #error "RTE does not support RTE_START_SEC_VAR_FAST_NO_INIT_BOOLEAN memory section"

#elif defined (RTE_STOP_SEC_VAR_FAST_NO_INIT_BOOLEAN)
  #undef RTE_STOP_SEC_VAR_FAST_NO_INIT_BOOLEAN
  #error "RTE does not support RTE_STOP_SEC_VAR_FAST_NO_INIT_BOOLEAN memory section"

#elif defined (RTE_START_SEC_VAR_FAST_NO_INIT_8)
  #undef RTE_START_SEC_VAR_FAST_NO_INIT_8
  #error "RTE does not support RTE_START_SEC_VAR_FAST_NO_INIT_8 memory section"

#elif defined (RTE_STOP_SEC_VAR_FAST_NO_INIT_8)
  #undef RTE_STOP_SEC_VAR_FAST_NO_INIT_8
  #error "RTE does not support RTE_STOP_SEC_VAR_FAST_NO_INIT_8 memory section"

#elif defined (RTE_START_SEC_VAR_FAST_NO_INIT_16)
  #undef RTE_START_SEC_VAR_FAST_NO_INIT_16
  #error "RTE does not support RTE_START_SEC_VAR_FAST_NO_INIT_16 memory section"

#elif defined (RTE_STOP_SEC_VAR_FAST_NO_INIT_16)
  #undef RTE_STOP_SEC_VAR_FAST_NO_INIT_16
  #error "RTE does not support RTE_STOP_SEC_VAR_FAST_NO_INIT_16 memory section"

#elif defined (RTE_START_SEC_VAR_FAST_NO_INIT_32)
  #undef RTE_START_SEC_VAR_FAST_NO_INIT_32
  #error "RTE does not support RTE_START_SEC_VAR_FAST_NO_INIT_32 memory section"

#elif defined (RTE_STOP_SEC_VAR_FAST_NO_INIT_32)
  #undef RTE_STOP_SEC_VAR_FAST_NO_INIT_32
  #error "RTE does not support RTE_STOP_SEC_VAR_FAST_NO_INIT_32 memory section"

#elif defined (RTE_START_SEC_VAR_FAST_NO_INIT_UNSPECIFIED)
  #undef RTE_START_SEC_VAR_FAST_NO_INIT_UNSPECIFIED
  #error "RTE does not support RTE_START_SEC_VAR_FAST_NO_INIT_UNSPECIFIED memory section"

#elif defined (RTE_STOP_SEC_VAR_FAST_NO_INIT_UNSPECIFIED)
  #undef RTE_STOP_SEC_VAR_FAST_NO_INIT_UNSPECIFIED
  #error "RTE does not support RTE_STOP_SEC_VAR_FAST_NO_INIT_UNSPECIFIED memory section"

#elif defined (RTE_START_SEC_VAR_FAST_CLEARED_BOOLEAN)
  #undef RTE_START_SEC_VAR_FAST_CLEARED_BOOLEAN
  #error "RTE does not support RTE_START_SEC_VAR_FAST_CLEARED_BOOLEAN memory section"

#elif defined (RTE_STOP_SEC_VAR_FAST_CLEARED_BOOLEAN)
  #undef RTE_STOP_SEC_VAR_FAST_CLEARED_BOOLEAN
  #error "RTE does not support RTE_STOP_SEC_VAR_FAST_CLEARED_BOOLEAN memory section"

#elif defined (RTE_START_SEC_VAR_FAST_CLEARED_8)
  #undef RTE_START_SEC_VAR_FAST_CLEARED_8
  #error "RTE does not support RTE_START_SEC_VAR_FAST_CLEARED_8 memory section"

#elif defined (RTE_STOP_SEC_VAR_FAST_CLEARED_8)
  #undef RTE_STOP_SEC_VAR_FAST_CLEARED_8
  #error "RTE does not support RTE_STOP_SEC_VAR_FAST_CLEARED_8 memory section"

#elif defined (RTE_START_SEC_VAR_FAST_CLEARED_16)
  #undef RTE_START_SEC_VAR_FAST_CLEARED_16
  #error "RTE does not support RTE_START_SEC_VAR_FAST_CLEARED_16 memory section"

#elif defined (RTE_STOP_SEC_VAR_FAST_CLEARED_16)
  #undef RTE_STOP_SEC_VAR_FAST_CLEARED_16
  #error "RTE does not support RTE_STOP_SEC_VAR_FAST_CLEARED_16 memory section"

#elif defined (RTE_START_SEC_VAR_FAST_CLEARED_32)
  #undef RTE_START_SEC_VAR_FAST_CLEARED_32
  #error "RTE does not support RTE_START_SEC_VAR_FAST_CLEARED_32 memory section"

#elif defined (RTE_STOP_SEC_VAR_FAST_CLEARED_32)
  #undef RTE_STOP_SEC_VAR_FAST_CLEARED_32
  #error "RTE does not support RTE_STOP_SEC_VAR_FAST_CLEARED_32 memory section"

#elif defined (RTE_START_SEC_VAR_FAST_CLEARED_UNSPECIFIED)
  #undef RTE_START_SEC_VAR_FAST_CLEARED_UNSPECIFIED
  #error "RTE does not support RTE_START_SEC_VAR_FAST_CLEARED_UNSPECIFIED memory section"

#elif defined (RTE_STOP_SEC_VAR_FAST_CLEARED_UNSPECIFIED)
  #undef RTE_STOP_SEC_VAR_FAST_CLEARED_UNSPECIFIED
  #error "RTE does not support RTE_STOP_SEC_VAR_FAST_CLEARED_UNSPECIFIED memory section"

#elif defined (RTE_START_SEC_VAR_FAST_INIT_BOOLEAN)
  #undef RTE_START_SEC_VAR_FAST_INIT_BOOLEAN
  #error "RTE does not support RTE_START_SEC_VAR_FAST_INIT_BOOLEAN memory section"

#elif defined (RTE_STOP_SEC_VAR_FAST_INIT_BOOLEAN)
  #undef RTE_STOP_SEC_VAR_FAST_INIT_BOOLEAN
  #error "RTE does not support RTE_STOP_SEC_VAR_FAST_INIT_BOOLEAN memory section"

#elif defined (RTE_START_SEC_VAR_FAST_INIT_8)
  #undef RTE_START_SEC_VAR_FAST_INIT_8
  #error "RTE does not support RTE_START_SEC_VAR_FAST_INIT_8 memory section"

#elif defined (RTE_STOP_SEC_VAR_FAST_INIT_8)
  #undef RTE_STOP_SEC_VAR_FAST_INIT_8
  #error "RTE does not support RTE_STOP_SEC_VAR_FAST_INIT_8 memory section"

#elif defined (RTE_START_SEC_VAR_FAST_INIT_16)
  #undef RTE_START_SEC_VAR_FAST_INIT_16
  #error "RTE does not support RTE_START_SEC_VAR_FAST_INIT_16 memory section"

#elif defined (RTE_STOP_SEC_VAR_FAST_INIT_16)
  #undef RTE_STOP_SEC_VAR_FAST_INIT_16
  #error "RTE does not support RTE_STOP_SEC_VAR_FAST_INIT_16 memory section"

#elif defined (RTE_START_SEC_VAR_FAST_INIT_32)
  #undef RTE_START_SEC_VAR_FAST_INIT_32
  #error "RTE does not support RTE_START_SEC_VAR_FAST_INIT_32 memory section"

#elif defined (RTE_STOP_SEC_VAR_FAST_INIT_32)
  #undef RTE_STOP_SEC_VAR_FAST_INIT_32
  #error "RTE does not support RTE_STOP_SEC_VAR_FAST_INIT_32 memory section"

#elif defined (RTE_START_SEC_VAR_FAST_INIT_UNSPECIFIED)
  #undef RTE_START_SEC_VAR_FAST_INIT_UNSPECIFIED
  #error "RTE does not support RTE_START_SEC_VAR_FAST_INIT_UNSPECIFIED memory section"

#elif defined (RTE_STOP_SEC_VAR_FAST_INIT_UNSPECIFIED)
  #undef RTE_STOP_SEC_VAR_FAST_INIT_UNSPECIFIED
  #error "RTE does not support RTE_STOP_SEC_VAR_FAST_INIT_UNSPECIFIED memory section"

#elif defined (RTE_START_SEC_VAR_FAST_POWER_ON_CLEARED_BOOLEAN)
  #undef RTE_START_SEC_VAR_FAST_POWER_ON_CLEARED_BOOLEAN
  #error "RTE does not support RTE_START_SEC_VAR_FAST_POWER_ON_CLEARED_BOOLEAN memory section"

#elif defined (RTE_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_BOOLEAN)
  #undef RTE_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_BOOLEAN
  #error "RTE does not support RTE_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_BOOLEAN memory section"

#elif defined (RTE_START_SEC_VAR_FAST_POWER_ON_CLEARED_8)
  #undef RTE_START_SEC_VAR_FAST_POWER_ON_CLEARED_8
  #error "RTE does not support RTE_START_SEC_VAR_FAST_POWER_ON_CLEARED_8 memory section"

#elif defined (RTE_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_8)
  #undef RTE_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_8
  #error "RTE does not support RTE_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_8 memory section"

#elif defined (RTE_START_SEC_VAR_FAST_POWER_ON_CLEARED_16)
  #undef RTE_START_SEC_VAR_FAST_POWER_ON_CLEARED_16
  #error "RTE does not support RTE_START_SEC_VAR_FAST_POWER_ON_CLEARED_16 memory section"

#elif defined (RTE_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_16)
  #undef RTE_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_16
  #error "RTE does not support RTE_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_16 memory section"

#elif defined (RTE_START_SEC_VAR_FAST_POWER_ON_CLEARED_32)
  #undef RTE_START_SEC_VAR_FAST_POWER_ON_CLEARED_32
  #error "RTE does not support RTE_START_SEC_VAR_FAST_POWER_ON_CLEARED_32 memory section"

#elif defined (RTE_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_32)
  #undef RTE_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_32
  #error "RTE does not support RTE_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_32 memory section"

#elif defined (RTE_START_SEC_VAR_FAST_POWER_ON_CLEARED_UNSPECIFIED)
  #undef RTE_START_SEC_VAR_FAST_POWER_ON_CLEARED_UNSPECIFIED
  #error "RTE does not support RTE_START_SEC_VAR_FAST_POWER_ON_CLEARED_UNSPECIFIED memory section"

#elif defined (RTE_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_UNSPECIFIED)
  #undef RTE_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_UNSPECIFIED
  #error "RTE does not support RTE_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_UNSPECIFIED memory section"

#elif defined (RTE_START_SEC_VAR_FAST_POWER_ON_INIT_BOOLEAN)
  #undef RTE_START_SEC_VAR_FAST_POWER_ON_INIT_BOOLEAN
  #error "RTE does not support RTE_START_SEC_VAR_FAST_POWER_ON_INIT_BOOLEAN memory section"

#elif defined (RTE_STOP_SEC_VAR_FAST_POWER_ON_INIT_BOOLEAN)
  #undef RTE_STOP_SEC_VAR_FAST_POWER_ON_INIT_BOOLEAN
  #error "RTE does not support RTE_STOP_SEC_VAR_FAST_POWER_ON_INIT_BOOLEAN memory section"

#elif defined (RTE_START_SEC_VAR_FAST_POWER_ON_INIT_8)
  #undef RTE_START_SEC_VAR_FAST_POWER_ON_INIT_8
  #error "RTE does not support RTE_START_SEC_VAR_FAST_POWER_ON_INIT_8 memory section"

#elif defined (RTE_STOP_SEC_VAR_FAST_POWER_ON_INIT_8)
  #undef RTE_STOP_SEC_VAR_FAST_POWER_ON_INIT_8
  #error "RTE does not support RTE_STOP_SEC_VAR_FAST_POWER_ON_INIT_8 memory section"

#elif defined (RTE_START_SEC_VAR_FAST_POWER_ON_INIT_16)
  #undef RTE_START_SEC_VAR_FAST_POWER_ON_INIT_16
  #error "RTE does not support RTE_START_SEC_VAR_FAST_POWER_ON_INIT_16 memory section"

#elif defined (RTE_STOP_SEC_VAR_FAST_POWER_ON_INIT_16)
  #undef RTE_STOP_SEC_VAR_FAST_POWER_ON_INIT_16
  #error "RTE does not support RTE_STOP_SEC_VAR_FAST_POWER_ON_INIT_16 memory section"

#elif defined (RTE_START_SEC_VAR_FAST_POWER_ON_INIT_32)
  #undef RTE_START_SEC_VAR_FAST_POWER_ON_INIT_32
  #error "RTE does not support RTE_START_SEC_VAR_FAST_POWER_ON_INIT_32 memory section"

#elif defined (RTE_STOP_SEC_VAR_FAST_POWER_ON_INIT_32)
  #undef RTE_STOP_SEC_VAR_FAST_POWER_ON_INIT_32
  #error "RTE does not support RTE_STOP_SEC_VAR_FAST_POWER_ON_INIT_32 memory section"

#elif defined (RTE_START_SEC_VAR_FAST_POWER_ON_INIT_UNSPECIFIED)
  #undef RTE_START_SEC_VAR_FAST_POWER_ON_INIT_UNSPECIFIED
  #error "RTE does not support RTE_START_SEC_VAR_FAST_POWER_ON_INIT_UNSPECIFIED memory section"

#elif defined (RTE_STOP_SEC_VAR_FAST_POWER_ON_INIT_UNSPECIFIED)
  #undef RTE_STOP_SEC_VAR_FAST_POWER_ON_INIT_UNSPECIFIED
  #error "RTE does not support RTE_STOP_SEC_VAR_FAST_POWER_ON_INIT_UNSPECIFIED memory section"

#elif defined (RTE_START_SEC_VAR_SLOW_BOOLEAN)
  #undef RTE_START_SEC_VAR_SLOW_BOOLEAN
  #error "RTE does not support RTE_START_SEC_VAR_SLOW_BOOLEAN memory section"

#elif defined (RTE_STOP_SEC_VAR_SLOW_BOOLEAN)
  #undef RTE_STOP_SEC_VAR_SLOW_BOOLEAN
  #error "RTE does not support RTE_STOP_SEC_VAR_SLOW_BOOLEAN memory section"

#elif defined (RTE_START_SEC_VAR_SLOW_8)
  #undef RTE_START_SEC_VAR_SLOW_8
  #error "RTE does not support RTE_START_SEC_VAR_SLOW_8 memory section"

#elif defined (RTE_STOP_SEC_VAR_SLOW_8)
  #undef RTE_STOP_SEC_VAR_SLOW_8
  #error "RTE does not support RTE_STOP_SEC_VAR_SLOW_8 memory section"

#elif defined (RTE_START_SEC_VAR_SLOW_16)
  #undef RTE_START_SEC_VAR_SLOW_16
  #error "RTE does not support RTE_START_SEC_VAR_SLOW_16 memory section"

#elif defined (RTE_STOP_SEC_VAR_SLOW_16)
  #undef RTE_STOP_SEC_VAR_SLOW_16
  #error "RTE does not support RTE_STOP_SEC_VAR_SLOW_16 memory section"

#elif defined (RTE_START_SEC_VAR_SLOW_32)
  #undef RTE_START_SEC_VAR_SLOW_32
  #error "RTE does not support RTE_START_SEC_VAR_SLOW_32 memory section"

#elif defined (RTE_STOP_SEC_VAR_SLOW_32)
  #undef RTE_STOP_SEC_VAR_SLOW_32
  #error "RTE does not support RTE_STOP_SEC_VAR_SLOW_32 memory section"

#elif defined (RTE_START_SEC_VAR_SLOW_UNSPECIFIED)
  #undef RTE_START_SEC_VAR_SLOW_UNSPECIFIED
  #error "RTE does not support RTE_START_SEC_VAR_SLOW_UNSPECIFIED memory section"

#elif defined (RTE_STOP_SEC_VAR_SLOW_UNSPECIFIED)
  #undef RTE_STOP_SEC_VAR_SLOW_UNSPECIFIED
  #error "RTE does not support RTE_STOP_SEC_VAR_SLOW_UNSPECIFIED memory section"

#elif defined (RTE_START_SEC_VAR_SLOW_NO_INIT_BOOLEAN)
  #undef RTE_START_SEC_VAR_SLOW_NO_INIT_BOOLEAN
  #error "RTE does not support RTE_START_SEC_VAR_SLOW_NO_INIT_BOOLEAN memory section"

#elif defined (RTE_STOP_SEC_VAR_SLOW_NO_INIT_BOOLEAN)
  #undef RTE_STOP_SEC_VAR_SLOW_NO_INIT_BOOLEAN
  #error "RTE does not support RTE_STOP_SEC_VAR_SLOW_NO_INIT_BOOLEAN memory section"

#elif defined (RTE_START_SEC_VAR_SLOW_NO_INIT_8)
  #undef RTE_START_SEC_VAR_SLOW_NO_INIT_8
  #error "RTE does not support RTE_START_SEC_VAR_SLOW_NO_INIT_8 memory section"

#elif defined (RTE_STOP_SEC_VAR_SLOW_NO_INIT_8)
  #undef RTE_STOP_SEC_VAR_SLOW_NO_INIT_8
  #error "RTE does not support RTE_STOP_SEC_VAR_SLOW_NO_INIT_8 memory section"

#elif defined (RTE_START_SEC_VAR_SLOW_NO_INIT_16)
  #undef RTE_START_SEC_VAR_SLOW_NO_INIT_16
  #error "RTE does not support RTE_START_SEC_VAR_SLOW_NO_INIT_16 memory section"

#elif defined (RTE_STOP_SEC_VAR_SLOW_NO_INIT_16)
  #undef RTE_STOP_SEC_VAR_SLOW_NO_INIT_16
  #error "RTE does not support RTE_STOP_SEC_VAR_SLOW_NO_INIT_16 memory section"

#elif defined (RTE_START_SEC_VAR_SLOW_NO_INIT_32)
  #undef RTE_START_SEC_VAR_SLOW_NO_INIT_32
  #error "RTE does not support RTE_START_SEC_VAR_SLOW_NO_INIT_32 memory section"

#elif defined (RTE_STOP_SEC_VAR_SLOW_NO_INIT_32)
  #undef RTE_STOP_SEC_VAR_SLOW_NO_INIT_32
  #error "RTE does not support RTE_STOP_SEC_VAR_SLOW_NO_INIT_32 memory section"

#elif defined (RTE_START_SEC_VAR_SLOW_NO_INIT_UNSPECIFIED)
  #undef RTE_START_SEC_VAR_SLOW_NO_INIT_UNSPECIFIED
  #error "RTE does not support RTE_START_SEC_VAR_SLOW_NO_INIT_UNSPECIFIED memory section"

#elif defined (RTE_STOP_SEC_VAR_SLOW_NO_INIT_UNSPECIFIED)
  #undef RTE_STOP_SEC_VAR_SLOW_NO_INIT_UNSPECIFIED
  #error "RTE does not support RTE_STOP_SEC_VAR_SLOW_NO_INIT_UNSPECIFIED memory section"

#elif defined (RTE_START_SEC_VAR_SLOW_CLEARED_BOOLEAN)
  #undef RTE_START_SEC_VAR_SLOW_CLEARED_BOOLEAN
  #error "RTE does not support RTE_START_SEC_VAR_SLOW_CLEARED_BOOLEAN memory section"

#elif defined (RTE_STOP_SEC_VAR_SLOW_CLEARED_BOOLEAN)
  #undef RTE_STOP_SEC_VAR_SLOW_CLEARED_BOOLEAN
  #error "RTE does not support RTE_STOP_SEC_VAR_SLOW_CLEARED_BOOLEAN memory section"

#elif defined (RTE_START_SEC_VAR_SLOW_CLEARED_8)
  #undef RTE_START_SEC_VAR_SLOW_CLEARED_8
  #error "RTE does not support RTE_START_SEC_VAR_SLOW_CLEARED_8 memory section"

#elif defined (RTE_STOP_SEC_VAR_SLOW_CLEARED_8)
  #undef RTE_STOP_SEC_VAR_SLOW_CLEARED_8
  #error "RTE does not support RTE_STOP_SEC_VAR_SLOW_CLEARED_8 memory section"

#elif defined (RTE_START_SEC_VAR_SLOW_CLEARED_16)
  #undef RTE_START_SEC_VAR_SLOW_CLEARED_16
  #error "RTE does not support RTE_START_SEC_VAR_SLOW_CLEARED_16 memory section"

#elif defined (RTE_STOP_SEC_VAR_SLOW_CLEARED_16)
  #undef RTE_STOP_SEC_VAR_SLOW_CLEARED_16
  #error "RTE does not support RTE_STOP_SEC_VAR_SLOW_CLEARED_16 memory section"

#elif defined (RTE_START_SEC_VAR_SLOW_CLEARED_32)
  #undef RTE_START_SEC_VAR_SLOW_CLEARED_32
  #error "RTE does not support RTE_START_SEC_VAR_SLOW_CLEARED_32 memory section"

#elif defined (RTE_STOP_SEC_VAR_SLOW_CLEARED_32)
  #undef RTE_STOP_SEC_VAR_SLOW_CLEARED_32
  #error "RTE does not support RTE_STOP_SEC_VAR_SLOW_CLEARED_32 memory section"

#elif defined (RTE_START_SEC_VAR_SLOW_CLEARED_UNSPECIFIED)
  #undef RTE_START_SEC_VAR_SLOW_CLEARED_UNSPECIFIED
  #error "RTE does not support RTE_START_SEC_VAR_SLOW_CLEARED_UNSPECIFIED memory section"

#elif defined (RTE_STOP_SEC_VAR_SLOW_CLEARED_UNSPECIFIED)
  #undef RTE_STOP_SEC_VAR_SLOW_CLEARED_UNSPECIFIED
  #error "RTE does not support RTE_STOP_SEC_VAR_SLOW_CLEARED_UNSPECIFIED memory section"

#elif defined (RTE_START_SEC_VAR_SLOW_INIT_BOOLEAN)
  #undef RTE_START_SEC_VAR_SLOW_INIT_BOOLEAN
  #error "RTE does not support RTE_START_SEC_VAR_SLOW_INIT_BOOLEAN memory section"

#elif defined (RTE_STOP_SEC_VAR_SLOW_INIT_BOOLEAN)
  #undef RTE_STOP_SEC_VAR_SLOW_INIT_BOOLEAN
  #error "RTE does not support RTE_STOP_SEC_VAR_SLOW_INIT_BOOLEAN memory section"

#elif defined (RTE_START_SEC_VAR_SLOW_INIT_8)
  #undef RTE_START_SEC_VAR_SLOW_INIT_8
  #error "RTE does not support RTE_START_SEC_VAR_SLOW_INIT_8 memory section"

#elif defined (RTE_STOP_SEC_VAR_SLOW_INIT_8)
  #undef RTE_STOP_SEC_VAR_SLOW_INIT_8
  #error "RTE does not support RTE_STOP_SEC_VAR_SLOW_INIT_8 memory section"

#elif defined (RTE_START_SEC_VAR_SLOW_INIT_16)
  #undef RTE_START_SEC_VAR_SLOW_INIT_16
  #error "RTE does not support RTE_START_SEC_VAR_SLOW_INIT_16 memory section"

#elif defined (RTE_STOP_SEC_VAR_SLOW_INIT_16)
  #undef RTE_STOP_SEC_VAR_SLOW_INIT_16
  #error "RTE does not support RTE_STOP_SEC_VAR_SLOW_INIT_16 memory section"

#elif defined (RTE_START_SEC_VAR_SLOW_INIT_32)
  #undef RTE_START_SEC_VAR_SLOW_INIT_32
  #error "RTE does not support RTE_START_SEC_VAR_SLOW_INIT_32 memory section"

#elif defined (RTE_STOP_SEC_VAR_SLOW_INIT_32)
  #undef RTE_STOP_SEC_VAR_SLOW_INIT_32
  #error "RTE does not support RTE_STOP_SEC_VAR_SLOW_INIT_32 memory section"

#elif defined (RTE_START_SEC_VAR_SLOW_INIT_UNSPECIFIED)
  #undef RTE_START_SEC_VAR_SLOW_INIT_UNSPECIFIED
  #error "RTE does not support RTE_START_SEC_VAR_SLOW_INIT_UNSPECIFIED memory section"

#elif defined (RTE_STOP_SEC_VAR_SLOW_INIT_UNSPECIFIED)
  #undef RTE_STOP_SEC_VAR_SLOW_INIT_UNSPECIFIED
  #error "RTE does not support RTE_STOP_SEC_VAR_SLOW_INIT_UNSPECIFIED memory section"

#elif defined (RTE_START_SEC_VAR_SLOW_POWER_ON_CLEARED_BOOLEAN)
  #undef RTE_START_SEC_VAR_SLOW_POWER_ON_CLEARED_BOOLEAN
  #error "RTE does not support RTE_START_SEC_VAR_SLOW_POWER_ON_CLEARED_BOOLEAN memory section"

#elif defined (RTE_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_BOOLEAN)
  #undef RTE_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_BOOLEAN
  #error "RTE does not support RTE_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_BOOLEAN memory section"

#elif defined (RTE_START_SEC_VAR_SLOW_POWER_ON_CLEARED_8)
  #undef RTE_START_SEC_VAR_SLOW_POWER_ON_CLEARED_8
  #error "RTE does not support RTE_START_SEC_VAR_SLOW_POWER_ON_CLEARED_8 memory section"

#elif defined (RTE_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_8)
  #undef RTE_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_8
  #error "RTE does not support RTE_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_8 memory section"

#elif defined (RTE_START_SEC_VAR_SLOW_POWER_ON_CLEARED_16)
  #undef RTE_START_SEC_VAR_SLOW_POWER_ON_CLEARED_16
  #error "RTE does not support RTE_START_SEC_VAR_SLOW_POWER_ON_CLEARED_16 memory section"

#elif defined (RTE_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_16)
  #undef RTE_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_16
  #error "RTE does not support RTE_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_16 memory section"

#elif defined (RTE_START_SEC_VAR_SLOW_POWER_ON_CLEARED_32)
  #undef RTE_START_SEC_VAR_SLOW_POWER_ON_CLEARED_32
  #error "RTE does not support RTE_START_SEC_VAR_SLOW_POWER_ON_CLEARED_32 memory section"

#elif defined (RTE_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_32)
  #undef RTE_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_32
  #error "RTE does not support RTE_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_32 memory section"

#elif defined (RTE_START_SEC_VAR_SLOW_POWER_ON_CLEARED_UNSPECIFIED)
  #undef RTE_START_SEC_VAR_SLOW_POWER_ON_CLEARED_UNSPECIFIED
  #error "RTE does not support RTE_START_SEC_VAR_SLOW_POWER_ON_CLEARED_UNSPECIFIED memory section"

#elif defined (RTE_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_UNSPECIFIED)
  #undef RTE_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_UNSPECIFIED
  #error "RTE does not support RTE_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_UNSPECIFIED memory section"

#elif defined (RTE_START_SEC_VAR_SLOW_POWER_ON_INIT_BOOLEAN)
  #undef RTE_START_SEC_VAR_SLOW_POWER_ON_INIT_BOOLEAN
  #error "RTE does not support RTE_START_SEC_VAR_SLOW_POWER_ON_INIT_BOOLEAN memory section"

#elif defined (RTE_STOP_SEC_VAR_SLOW_POWER_ON_INIT_BOOLEAN)
  #undef RTE_STOP_SEC_VAR_SLOW_POWER_ON_INIT_BOOLEAN
  #error "RTE does not support RTE_STOP_SEC_VAR_SLOW_POWER_ON_INIT_BOOLEAN memory section"

#elif defined (RTE_START_SEC_VAR_SLOW_POWER_ON_INIT_8)
  #undef RTE_START_SEC_VAR_SLOW_POWER_ON_INIT_8
  #error "RTE does not support RTE_START_SEC_VAR_SLOW_POWER_ON_INIT_8 memory section"

#elif defined (RTE_STOP_SEC_VAR_SLOW_POWER_ON_INIT_8)
  #undef RTE_STOP_SEC_VAR_SLOW_POWER_ON_INIT_8
  #error "RTE does not support RTE_STOP_SEC_VAR_SLOW_POWER_ON_INIT_8 memory section"

#elif defined (RTE_START_SEC_VAR_SLOW_POWER_ON_INIT_16)
  #undef RTE_START_SEC_VAR_SLOW_POWER_ON_INIT_16
  #error "RTE does not support RTE_START_SEC_VAR_SLOW_POWER_ON_INIT_16 memory section"

#elif defined (RTE_STOP_SEC_VAR_SLOW_POWER_ON_INIT_16)
  #undef RTE_STOP_SEC_VAR_SLOW_POWER_ON_INIT_16
  #error "RTE does not support RTE_STOP_SEC_VAR_SLOW_POWER_ON_INIT_16 memory section"

#elif defined (RTE_START_SEC_VAR_SLOW_POWER_ON_INIT_32)
  #undef RTE_START_SEC_VAR_SLOW_POWER_ON_INIT_32
  #error "RTE does not support RTE_START_SEC_VAR_SLOW_POWER_ON_INIT_32 memory section"

#elif defined (RTE_STOP_SEC_VAR_SLOW_POWER_ON_INIT_32)
  #undef RTE_STOP_SEC_VAR_SLOW_POWER_ON_INIT_32
  #error "RTE does not support RTE_STOP_SEC_VAR_SLOW_POWER_ON_INIT_32 memory section"

#elif defined (RTE_START_SEC_VAR_SLOW_POWER_ON_INIT_UNSPECIFIED)
  #undef RTE_START_SEC_VAR_SLOW_POWER_ON_INIT_UNSPECIFIED
  #error "RTE does not support RTE_START_SEC_VAR_SLOW_POWER_ON_INIT_UNSPECIFIED memory section"

#elif defined (RTE_STOP_SEC_VAR_SLOW_POWER_ON_INIT_UNSPECIFIED)
  #undef RTE_STOP_SEC_VAR_SLOW_POWER_ON_INIT_UNSPECIFIED
  #error "RTE does not support RTE_STOP_SEC_VAR_SLOW_POWER_ON_INIT_UNSPECIFIED memory section"

#elif defined (RTE_START_SEC_INTERNAL_VAR_BOOLEAN)
  #undef RTE_START_SEC_INTERNAL_VAR_BOOLEAN
  
//  #pragma ghs section bss=".bss.DEFAULT_RAM_INTERNAL_VAR_CLEARED"
//  #pragma ghs section data=".data.DEFAULT_RAM_INTERNAL_VAR_INIT"

#elif defined (RTE_STOP_SEC_INTERNAL_VAR_BOOLEAN)
  #undef RTE_STOP_SEC_INTERNAL_VAR_BOOLEAN
  
//  #pragma ghs section data=default
//  #pragma ghs section bss=default

#elif defined (RTE_START_SEC_INTERNAL_VAR_8)
  #undef RTE_START_SEC_INTERNAL_VAR_8
  
//  #pragma ghs section bss=".bss.DEFAULT_RAM_INTERNAL_VAR_CLEARED"
//  #pragma ghs section data=".data.DEFAULT_RAM_INTERNAL_VAR_INIT"

#elif defined (RTE_STOP_SEC_INTERNAL_VAR_8)
  #undef RTE_STOP_SEC_INTERNAL_VAR_8
  
//  #pragma ghs section data=default
//  #pragma ghs section bss=default

#elif defined (RTE_START_SEC_INTERNAL_VAR_16)
  #undef RTE_START_SEC_INTERNAL_VAR_16
  
//  #pragma ghs section bss=".bss.DEFAULT_RAM_INTERNAL_VAR_CLEARED"
//  #pragma ghs section data=".data.DEFAULT_RAM_INTERNAL_VAR_INIT"

#elif defined (RTE_STOP_SEC_INTERNAL_VAR_16)
  #undef RTE_STOP_SEC_INTERNAL_VAR_16
  
//  #pragma ghs section data=default
//  #pragma ghs section bss=default

#elif defined (RTE_START_SEC_INTERNAL_VAR_32)
  #undef RTE_START_SEC_INTERNAL_VAR_32
  
//  #pragma ghs section bss=".bss.DEFAULT_RAM_INTERNAL_VAR_CLEARED"
//  #pragma ghs section data=".data.DEFAULT_RAM_INTERNAL_VAR_INIT"

#elif defined (RTE_STOP_SEC_INTERNAL_VAR_32)
  #undef RTE_STOP_SEC_INTERNAL_VAR_32
  
//  #pragma ghs section data=default
//  #pragma ghs section bss=default

#elif defined (RTE_START_SEC_INTERNAL_VAR_UNSPECIFIED)
  #undef RTE_START_SEC_INTERNAL_VAR_UNSPECIFIED
  
//  #pragma ghs section bss=".bss.DEFAULT_RAM_INTERNAL_VAR_CLEARED"
//  #pragma ghs section data=".data.DEFAULT_RAM_INTERNAL_VAR_INIT"

#elif defined (RTE_STOP_SEC_INTERNAL_VAR_UNSPECIFIED)
  #undef RTE_STOP_SEC_INTERNAL_VAR_UNSPECIFIED
  
//  #pragma ghs section data=default
//  #pragma ghs section bss=default

#elif defined (RTE_START_SEC_INTERNAL_VAR_NO_INIT_BOOLEAN)
  #undef RTE_START_SEC_INTERNAL_VAR_NO_INIT_BOOLEAN
  
//  #pragma ghs section bss=".bss.DEFAULT_RAM_INTERNAL_VAR_NO_INIT"

#elif defined (RTE_STOP_SEC_INTERNAL_VAR_NO_INIT_BOOLEAN)
  #undef RTE_STOP_SEC_INTERNAL_VAR_NO_INIT_BOOLEAN
  
//  #pragma ghs section bss=default

#elif defined (RTE_START_SEC_INTERNAL_VAR_NO_INIT_8)
  #undef RTE_START_SEC_INTERNAL_VAR_NO_INIT_8
  
//  #pragma ghs section bss=".bss.DEFAULT_RAM_INTERNAL_VAR_NO_INIT"

#elif defined (RTE_STOP_SEC_INTERNAL_VAR_NO_INIT_8)
  #undef RTE_STOP_SEC_INTERNAL_VAR_NO_INIT_8
  
//  #pragma ghs section bss=default

#elif defined (RTE_START_SEC_INTERNAL_VAR_NO_INIT_16)
  #undef RTE_START_SEC_INTERNAL_VAR_NO_INIT_16
  
//  #pragma ghs section bss=".bss.DEFAULT_RAM_INTERNAL_VAR_NO_INIT"

#elif defined (RTE_STOP_SEC_INTERNAL_VAR_NO_INIT_16)
  #undef RTE_STOP_SEC_INTERNAL_VAR_NO_INIT_16
  
//  #pragma ghs section bss=default

#elif defined (RTE_START_SEC_INTERNAL_VAR_NO_INIT_32)
  #undef RTE_START_SEC_INTERNAL_VAR_NO_INIT_32
  
//  #pragma ghs section bss=".bss.DEFAULT_RAM_INTERNAL_VAR_NO_INIT"

#elif defined (RTE_STOP_SEC_INTERNAL_VAR_NO_INIT_32)
  #undef RTE_STOP_SEC_INTERNAL_VAR_NO_INIT_32
  
//  #pragma ghs section bss=default

#elif defined (RTE_START_SEC_INTERNAL_VAR_NO_INIT_UNSPECIFIED)
  #undef RTE_START_SEC_INTERNAL_VAR_NO_INIT_UNSPECIFIED
  
//  #pragma ghs section bss=".bss.DEFAULT_RAM_INTERNAL_VAR_NO_INIT"

#elif defined (RTE_STOP_SEC_INTERNAL_VAR_NO_INIT_UNSPECIFIED)
  #undef RTE_STOP_SEC_INTERNAL_VAR_NO_INIT_UNSPECIFIED
  
//  #pragma ghs section bss=default

#elif defined (RTE_START_SEC_INTERNAL_VAR_CLEARED_BOOLEAN)
  #undef RTE_START_SEC_INTERNAL_VAR_CLEARED_BOOLEAN
  
//  #pragma ghs section bss=".bss.DEFAULT_RAM_INTERNAL_VAR_CLEARED"

#elif defined (RTE_STOP_SEC_INTERNAL_VAR_CLEARED_BOOLEAN)
  #undef RTE_STOP_SEC_INTERNAL_VAR_CLEARED_BOOLEAN
  
//  #pragma ghs section bss=default

#elif defined (RTE_START_SEC_INTERNAL_VAR_CLEARED_8)
  #undef RTE_START_SEC_INTERNAL_VAR_CLEARED_8
  
//  #pragma ghs section bss=".bss.DEFAULT_RAM_INTERNAL_VAR_CLEARED"

#elif defined (RTE_STOP_SEC_INTERNAL_VAR_CLEARED_8)
  #undef RTE_STOP_SEC_INTERNAL_VAR_CLEARED_8
  
//  #pragma ghs section bss=default

#elif defined (RTE_START_SEC_INTERNAL_VAR_CLEARED_16)
  #undef RTE_START_SEC_INTERNAL_VAR_CLEARED_16
  
//  #pragma ghs section bss=".bss.DEFAULT_RAM_INTERNAL_VAR_CLEARED"

#elif defined (RTE_STOP_SEC_INTERNAL_VAR_CLEARED_16)
  #undef RTE_STOP_SEC_INTERNAL_VAR_CLEARED_16
  
//  #pragma ghs section bss=default

#elif defined (RTE_START_SEC_INTERNAL_VAR_CLEARED_32)
  #undef RTE_START_SEC_INTERNAL_VAR_CLEARED_32
  
//  #pragma ghs section bss=".bss.DEFAULT_RAM_INTERNAL_VAR_CLEARED"

#elif defined (RTE_STOP_SEC_INTERNAL_VAR_CLEARED_32)
  #undef RTE_STOP_SEC_INTERNAL_VAR_CLEARED_32
  
//  #pragma ghs section bss=default

#elif defined (RTE_START_SEC_INTERNAL_VAR_CLEARED_UNSPECIFIED)
  #undef RTE_START_SEC_INTERNAL_VAR_CLEARED_UNSPECIFIED
  
//  #pragma ghs section bss=".bss.DEFAULT_RAM_INTERNAL_VAR_CLEARED"

#elif defined (RTE_STOP_SEC_INTERNAL_VAR_CLEARED_UNSPECIFIED)
  #undef RTE_STOP_SEC_INTERNAL_VAR_CLEARED_UNSPECIFIED
  
//  #pragma ghs section bss=default

#elif defined (RTE_START_SEC_INTERNAL_VAR_INIT_BOOLEAN)
  #undef RTE_START_SEC_INTERNAL_VAR_INIT_BOOLEAN
  
//  #pragma ghs section data=".data.DEFAULT_RAM_INTERNAL_VAR_INIT"

#elif defined (RTE_STOP_SEC_INTERNAL_VAR_INIT_BOOLEAN)
  #undef RTE_STOP_SEC_INTERNAL_VAR_INIT_BOOLEAN
  
//  #pragma ghs section data=default

#elif defined (RTE_START_SEC_INTERNAL_VAR_INIT_8)
  #undef RTE_START_SEC_INTERNAL_VAR_INIT_8
  
//  #pragma ghs section data=".data.DEFAULT_RAM_INTERNAL_VAR_INIT"

#elif defined (RTE_STOP_SEC_INTERNAL_VAR_INIT_8)
  #undef RTE_STOP_SEC_INTERNAL_VAR_INIT_8
  
//  #pragma ghs section data=default

#elif defined (RTE_START_SEC_INTERNAL_VAR_INIT_16)
  #undef RTE_START_SEC_INTERNAL_VAR_INIT_16
  
//  #pragma ghs section data=".data.DEFAULT_RAM_INTERNAL_VAR_INIT"

#elif defined (RTE_STOP_SEC_INTERNAL_VAR_INIT_16)
  #undef RTE_STOP_SEC_INTERNAL_VAR_INIT_16
  
//  #pragma ghs section data=default

#elif defined (RTE_START_SEC_INTERNAL_VAR_INIT_32)
  #undef RTE_START_SEC_INTERNAL_VAR_INIT_32
  
//  #pragma ghs section data=".data.DEFAULT_RAM_INTERNAL_VAR_INIT"

#elif defined (RTE_STOP_SEC_INTERNAL_VAR_INIT_32)
  #undef RTE_STOP_SEC_INTERNAL_VAR_INIT_32
  
//  #pragma ghs section data=default

#elif defined (RTE_START_SEC_INTERNAL_VAR_INIT_UNSPECIFIED)
  #undef RTE_START_SEC_INTERNAL_VAR_INIT_UNSPECIFIED
  
//  #pragma ghs section data=".data.DEFAULT_RAM_INTERNAL_VAR_INIT"

#elif defined (RTE_STOP_SEC_INTERNAL_VAR_INIT_UNSPECIFIED)
  #undef RTE_STOP_SEC_INTERNAL_VAR_INIT_UNSPECIFIED
  
//  #pragma ghs section data=default

#elif defined (RTE_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_BOOLEAN)
  #undef RTE_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_BOOLEAN
  #error "RTE does not support RTE_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_BOOLEAN memory section"

#elif defined (RTE_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_BOOLEAN)
  #undef RTE_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_BOOLEAN
  #error "RTE does not support RTE_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_BOOLEAN memory section"

#elif defined (RTE_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_8)
  #undef RTE_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_8
  #error "RTE does not support RTE_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_8 memory section"

#elif defined (RTE_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_8)
  #undef RTE_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_8
  #error "RTE does not support RTE_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_8 memory section"

#elif defined (RTE_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_16)
  #undef RTE_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_16
  #error "RTE does not support RTE_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_16 memory section"

#elif defined (RTE_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_16)
  #undef RTE_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_16
  #error "RTE does not support RTE_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_16 memory section"

#elif defined (RTE_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_32)
  #undef RTE_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_32
  #error "RTE does not support RTE_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_32 memory section"

#elif defined (RTE_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_32)
  #undef RTE_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_32
  #error "RTE does not support RTE_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_32 memory section"

#elif defined (RTE_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_UNSPECIFIED)
  #undef RTE_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_UNSPECIFIED
  #error "RTE does not support RTE_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_UNSPECIFIED memory section"

#elif defined (RTE_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_UNSPECIFIED)
  #undef RTE_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_UNSPECIFIED
  #error "RTE does not support RTE_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_UNSPECIFIED memory section"

#elif defined (RTE_START_SEC_INTERNAL_VAR_POWER_ON_INIT_BOOLEAN)
  #undef RTE_START_SEC_INTERNAL_VAR_POWER_ON_INIT_BOOLEAN
  #error "RTE does not support RTE_START_SEC_INTERNAL_VAR_POWER_ON_INIT_BOOLEAN memory section"

#elif defined (RTE_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_BOOLEAN)
  #undef RTE_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_BOOLEAN
  #error "RTE does not support RTE_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_BOOLEAN memory section"

#elif defined (RTE_START_SEC_INTERNAL_VAR_POWER_ON_INIT_8)
  #undef RTE_START_SEC_INTERNAL_VAR_POWER_ON_INIT_8
  #error "RTE does not support RTE_START_SEC_INTERNAL_VAR_POWER_ON_INIT_8 memory section"

#elif defined (RTE_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_8)
  #undef RTE_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_8
  #error "RTE does not support RTE_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_8 memory section"

#elif defined (RTE_START_SEC_INTERNAL_VAR_POWER_ON_INIT_16)
  #undef RTE_START_SEC_INTERNAL_VAR_POWER_ON_INIT_16
  #error "RTE does not support RTE_START_SEC_INTERNAL_VAR_POWER_ON_INIT_16 memory section"

#elif defined (RTE_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_16)
  #undef RTE_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_16
  #error "RTE does not support RTE_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_16 memory section"

#elif defined (RTE_START_SEC_INTERNAL_VAR_POWER_ON_INIT_32)
  #undef RTE_START_SEC_INTERNAL_VAR_POWER_ON_INIT_32
  #error "RTE does not support RTE_START_SEC_INTERNAL_VAR_POWER_ON_INIT_32 memory section"

#elif defined (RTE_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_32)
  #undef RTE_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_32
  #error "RTE does not support RTE_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_32 memory section"

#elif defined (RTE_START_SEC_INTERNAL_VAR_POWER_ON_INIT_UNSPECIFIED)
  #undef RTE_START_SEC_INTERNAL_VAR_POWER_ON_INIT_UNSPECIFIED
  #error "RTE does not support RTE_START_SEC_INTERNAL_VAR_POWER_ON_INIT_UNSPECIFIED memory section"

#elif defined (RTE_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_UNSPECIFIED)
  #undef RTE_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_UNSPECIFIED
  #error "RTE does not support RTE_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_UNSPECIFIED memory section"

#elif defined (RTE_START_SEC_VAR_SAVED_ZONE_BOOLEAN)
  #undef RTE_START_SEC_VAR_SAVED_ZONE_BOOLEAN
  
//  #pragma ghs section bss=".bss.DEFAULT_RAM_VAR_SAVED_ZONE"
//  #pragma ghs section data=".data.DEFAULT_RAM_VAR_SAVED_ZONE"

#elif defined (RTE_STOP_SEC_VAR_SAVED_ZONE_BOOLEAN)
  #undef RTE_STOP_SEC_VAR_SAVED_ZONE_BOOLEAN
  
//  #pragma ghs section data=default
//  #pragma ghs section bss=default

#elif defined (RTE_START_SEC_VAR_SAVED_ZONE_8)
  #undef RTE_START_SEC_VAR_SAVED_ZONE_8
  
//  #pragma ghs section bss=".bss.DEFAULT_RAM_VAR_SAVED_ZONE"
//  #pragma ghs section data=".data.DEFAULT_RAM_VAR_SAVED_ZONE"

#elif defined (RTE_STOP_SEC_VAR_SAVED_ZONE_8)
  #undef RTE_STOP_SEC_VAR_SAVED_ZONE_8
  
//  #pragma ghs section data=default
//  #pragma ghs section bss=default

#elif defined (RTE_START_SEC_VAR_SAVED_ZONE_16)
  #undef RTE_START_SEC_VAR_SAVED_ZONE_16
  
//  #pragma ghs section bss=".bss.DEFAULT_RAM_VAR_SAVED_ZONE"
//  #pragma ghs section data=".data.DEFAULT_RAM_VAR_SAVED_ZONE"

#elif defined (RTE_STOP_SEC_VAR_SAVED_ZONE_16)
  #undef RTE_STOP_SEC_VAR_SAVED_ZONE_16
  
//  #pragma ghs section data=default
//  #pragma ghs section bss=default

#elif defined (RTE_START_SEC_VAR_SAVED_ZONE_32)
  #undef RTE_START_SEC_VAR_SAVED_ZONE_32
  
//  #pragma ghs section bss=".bss.DEFAULT_RAM_VAR_SAVED_ZONE"
//  #pragma ghs section data=".data.DEFAULT_RAM_VAR_SAVED_ZONE"

#elif defined (RTE_STOP_SEC_VAR_SAVED_ZONE_32)
  #undef RTE_STOP_SEC_VAR_SAVED_ZONE_32
  
//  #pragma ghs section data=default
//  #pragma ghs section bss=default

#elif defined (RTE_START_SEC_VAR_SAVED_ZONE_UNSPECIFIED)
  #undef RTE_START_SEC_VAR_SAVED_ZONE_UNSPECIFIED
  
//  #pragma ghs section bss=".bss.DEFAULT_RAM_VAR_SAVED_ZONE"
//  #pragma ghs section data=".data.DEFAULT_RAM_VAR_SAVED_ZONE"

#elif defined (RTE_STOP_SEC_VAR_SAVED_ZONE_UNSPECIFIED)
  #undef RTE_STOP_SEC_VAR_SAVED_ZONE_UNSPECIFIED
  
//  #pragma ghs section data=default
//  #pragma ghs section bss=default

#elif defined (RTE_START_SEC_CONST_SAVED_RECOVERY_ZONE_BOOLEAN)
  #undef RTE_START_SEC_CONST_SAVED_RECOVERY_ZONE_BOOLEAN
  
//  #pragma ghs section rodata=".rodata.DEFAULT_ROM_CONST_SAVED_RECOVERY_ZONE"

#elif defined (RTE_STOP_SEC_CONST_SAVED_RECOVERY_ZONE_BOOLEAN)
  #undef RTE_STOP_SEC_CONST_SAVED_RECOVERY_ZONE_BOOLEAN
  
//  #pragma ghs section rodata=default

#elif defined (RTE_START_SEC_CONST_SAVED_RECOVERY_ZONE_8)
  #undef RTE_START_SEC_CONST_SAVED_RECOVERY_ZONE_8
  
//  #pragma ghs section rodata=".rodata.DEFAULT_ROM_CONST_SAVED_RECOVERY_ZONE"

#elif defined (RTE_STOP_SEC_CONST_SAVED_RECOVERY_ZONE_8)
  #undef RTE_STOP_SEC_CONST_SAVED_RECOVERY_ZONE_8
  
//  #pragma ghs section rodata=default

#elif defined (RTE_START_SEC_CONST_SAVED_RECOVERY_ZONE_16)
  #undef RTE_START_SEC_CONST_SAVED_RECOVERY_ZONE_16
  
//  #pragma ghs section rodata=".rodata.DEFAULT_ROM_CONST_SAVED_RECOVERY_ZONE"

#elif defined (RTE_STOP_SEC_CONST_SAVED_RECOVERY_ZONE_16)
  #undef RTE_STOP_SEC_CONST_SAVED_RECOVERY_ZONE_16
  
//  #pragma ghs section rodata=default

#elif defined (RTE_START_SEC_CONST_SAVED_RECOVERY_ZONE_32)
  #undef RTE_START_SEC_CONST_SAVED_RECOVERY_ZONE_32
  
//  #pragma ghs section rodata=".rodata.DEFAULT_ROM_CONST_SAVED_RECOVERY_ZONE"

#elif defined (RTE_STOP_SEC_CONST_SAVED_RECOVERY_ZONE_32)
  #undef RTE_STOP_SEC_CONST_SAVED_RECOVERY_ZONE_32
  
//  #pragma ghs section rodata=default

#elif defined (RTE_START_SEC_CONST_SAVED_RECOVERY_ZONE_UNSPECIFIED)
  #undef RTE_START_SEC_CONST_SAVED_RECOVERY_ZONE_UNSPECIFIED
  
//  #pragma ghs section rodata=".rodata.DEFAULT_ROM_CONST_SAVED_RECOVERY_ZONE"

#elif defined (RTE_STOP_SEC_CONST_SAVED_RECOVERY_ZONE_UNSPECIFIED)
  #undef RTE_STOP_SEC_CONST_SAVED_RECOVERY_ZONE_UNSPECIFIED
  
//  #pragma ghs section rodata=default

#elif defined (RTE_START_SEC_CONST_BOOLEAN)
  #undef RTE_START_SEC_CONST_BOOLEAN
  
//  #pragma ghs section rodata=".rodata.DEFAULT_ROM_CONST"

#elif defined (RTE_STOP_SEC_CONST_BOOLEAN)
  #undef RTE_STOP_SEC_CONST_BOOLEAN
  
//  #pragma ghs section rodata=default

#elif defined (RTE_START_SEC_CONST_8)
  #undef RTE_START_SEC_CONST_8
  
//  #pragma ghs section rodata=".rodata.DEFAULT_ROM_CONST"

#elif defined (RTE_STOP_SEC_CONST_8)
  #undef RTE_STOP_SEC_CONST_8
  
//  #pragma ghs section rodata=default

#elif defined (RTE_START_SEC_CONST_16)
  #undef RTE_START_SEC_CONST_16
  
//  #pragma ghs section rodata=".rodata.DEFAULT_ROM_CONST"

#elif defined (RTE_STOP_SEC_CONST_16)
  #undef RTE_STOP_SEC_CONST_16
  
//  #pragma ghs section rodata=default

#elif defined (RTE_START_SEC_CONST_32)
  #undef RTE_START_SEC_CONST_32
  
//  #pragma ghs section rodata=".rodata.DEFAULT_ROM_CONST"

#elif defined (RTE_STOP_SEC_CONST_32)
  #undef RTE_STOP_SEC_CONST_32
  
//  #pragma ghs section rodata=default

#elif defined (RTE_START_SEC_CONST_UNSPECIFIED)
  #undef RTE_START_SEC_CONST_UNSPECIFIED
  
//  #pragma ghs section rodata=".rodata.DEFAULT_ROM_CONST"

#elif defined (RTE_STOP_SEC_CONST_UNSPECIFIED)
  #undef RTE_STOP_SEC_CONST_UNSPECIFIED
  
//  #pragma ghs section rodata=default

#elif defined (RTE_START_SEC_CALIB_BOOLEAN)
  #undef RTE_START_SEC_CALIB_BOOLEAN
  
//  #pragma ghs section rodata=".rodata.DEFAULT_ROM_CALIB"

#elif defined (RTE_STOP_SEC_CALIB_BOOLEAN)
  #undef RTE_STOP_SEC_CALIB_BOOLEAN
  
//  #pragma ghs section rodata=default

#elif defined (RTE_START_SEC_CALIB_8)
  #undef RTE_START_SEC_CALIB_8
  
//  #pragma ghs section rodata=".rodata.DEFAULT_ROM_CALIB"

#elif defined (RTE_STOP_SEC_CALIB_8)
  #undef RTE_STOP_SEC_CALIB_8
  
//  #pragma ghs section rodata=default

#elif defined (RTE_START_SEC_CALIB_16)
  #undef RTE_START_SEC_CALIB_16
  
//  #pragma ghs section rodata=".rodata.DEFAULT_ROM_CALIB"

#elif defined (RTE_STOP_SEC_CALIB_16)
  #undef RTE_STOP_SEC_CALIB_16
  
//  #pragma ghs section rodata=default

#elif defined (RTE_START_SEC_CALIB_32)
  #undef RTE_START_SEC_CALIB_32
  
//  #pragma ghs section rodata=".rodata.DEFAULT_ROM_CALIB"

#elif defined (RTE_STOP_SEC_CALIB_32)
  #undef RTE_STOP_SEC_CALIB_32
  
//  #pragma ghs section rodata=default

#elif defined (RTE_START_SEC_CALIB_UNSPECIFIED)
  #undef RTE_START_SEC_CALIB_UNSPECIFIED
  
//  #pragma ghs section rodata=".rodata.DEFAULT_ROM_CALIB"

#elif defined (RTE_STOP_SEC_CALIB_UNSPECIFIED)
  #undef RTE_STOP_SEC_CALIB_UNSPECIFIED
  
//  #pragma ghs section rodata=default

#elif defined (RTE_START_SEC_CARTO_BOOLEAN)
  #undef RTE_START_SEC_CARTO_BOOLEAN
  #error "RTE does not support RTE_START_SEC_CARTO_BOOLEAN memory section"

#elif defined (RTE_STOP_SEC_CARTO_BOOLEAN)
  #undef RTE_STOP_SEC_CARTO_BOOLEAN
  #error "RTE does not support RTE_STOP_SEC_CARTO_BOOLEAN memory section"

#elif defined (RTE_START_SEC_CARTO_8)
  #undef RTE_START_SEC_CARTO_8
  #error "RTE does not support RTE_START_SEC_CARTO_8 memory section"

#elif defined (RTE_STOP_SEC_CARTO_8)
  #undef RTE_STOP_SEC_CARTO_8
  #error "RTE does not support RTE_STOP_SEC_CARTO_8 memory section"

#elif defined (RTE_START_SEC_CARTO_16)
  #undef RTE_START_SEC_CARTO_16
  #error "RTE does not support RTE_START_SEC_CARTO_16 memory section"

#elif defined (RTE_STOP_SEC_CARTO_16)
  #undef RTE_STOP_SEC_CARTO_16
  #error "RTE does not support RTE_STOP_SEC_CARTO_16 memory section"

#elif defined (RTE_START_SEC_CARTO_32)
  #undef RTE_START_SEC_CARTO_32
  #error "RTE does not support RTE_START_SEC_CARTO_32 memory section"

#elif defined (RTE_STOP_SEC_CARTO_32)
  #undef RTE_STOP_SEC_CARTO_32
  #error "RTE does not support RTE_STOP_SEC_CARTO_32 memory section"

#elif defined (RTE_START_SEC_CARTO_UNSPECIFIED)
  #undef RTE_START_SEC_CARTO_UNSPECIFIED
  #error "RTE does not support RTE_START_SEC_CARTO_UNSPECIFIED memory section"

#elif defined (RTE_STOP_SEC_CARTO_UNSPECIFIED)
  #undef RTE_STOP_SEC_CARTO_UNSPECIFIED
  #error "RTE does not support RTE_STOP_SEC_CARTO_UNSPECIFIED memory section"

#elif defined (RTE_START_SEC_CONFIG_DATA_BOOLEAN)
  #undef RTE_START_SEC_CONFIG_DATA_BOOLEAN
  
//  #pragma ghs section rodata=".rodata.DEFAULT_ROM_CONFIG_DATA"

#elif defined (RTE_STOP_SEC_CONFIG_DATA_BOOLEAN)
  #undef RTE_STOP_SEC_CONFIG_DATA_BOOLEAN
  
//  #pragma ghs section rodata=default

#elif defined (RTE_START_SEC_CONFIG_DATA_8)
  #undef RTE_START_SEC_CONFIG_DATA_8
  
//  #pragma ghs section rodata=".rodata.DEFAULT_ROM_CONFIG_DATA"

#elif defined (RTE_STOP_SEC_CONFIG_DATA_8)
  #undef RTE_STOP_SEC_CONFIG_DATA_8
  
//  #pragma ghs section rodata=default

#elif defined (RTE_START_SEC_CONFIG_DATA_16)
  #undef RTE_START_SEC_CONFIG_DATA_16
  
//  #pragma ghs section rodata=".rodata.DEFAULT_ROM_CONFIG_DATA"

#elif defined (RTE_STOP_SEC_CONFIG_DATA_16)
  #undef RTE_STOP_SEC_CONFIG_DATA_16
  
//  #pragma ghs section rodata=default

#elif defined (RTE_START_SEC_CONFIG_DATA_32)
  #undef RTE_START_SEC_CONFIG_DATA_32
  
//  #pragma ghs section rodata=".rodata.DEFAULT_ROM_CONFIG_DATA"

#elif defined (RTE_STOP_SEC_CONFIG_DATA_32)
  #undef RTE_STOP_SEC_CONFIG_DATA_32
  
//  #pragma ghs section rodata=default

#elif defined (RTE_START_SEC_CONFIG_DATA_UNSPECIFIED)
  #undef RTE_START_SEC_CONFIG_DATA_UNSPECIFIED
  
//  #pragma ghs section rodata=".rodata.DEFAULT_ROM_CONFIG_DATA"

#elif defined (RTE_STOP_SEC_CONFIG_DATA_UNSPECIFIED)
  #undef RTE_STOP_SEC_CONFIG_DATA_UNSPECIFIED
  
//  #pragma ghs section rodata=default

#elif defined (RTE_START_SEC_CODE)
  #undef RTE_START_SEC_CODE
  
//  #pragma ghs section text=".text.DEFAULT_CODE"
//  #pragma ghs section rodata=".rodata.DEFAULT_ROM_CONST"
//  #pragma ghs section bss=".bss.DEFAULT_RAM_VAR_CLEARED"
//  #pragma ghs section data=".data.DEFAULT_RAM_VAR_INIT"

#elif defined (RTE_STOP_SEC_CODE)
  #undef RTE_STOP_SEC_CODE
  
//  #pragma ghs section data=default
//  #pragma ghs section bss=default
//  #pragma ghs section rodata=default
//  #pragma ghs section text=default

#elif defined (RTE_START_SEC_CALLOUT_CODE)
  #undef RTE_START_SEC_CALLOUT_CODE
  #error "RTE does not support RTE_START_SEC_CALLOUT_CODE memory section"

#elif defined (RTE_STOP_SEC_CALLOUT_CODE)
  #undef RTE_STOP_SEC_CALLOUT_CODE
  #error "RTE does not support RTE_STOP_SEC_CALLOUT_CODE memory section"

#elif defined (RTE_START_SEC_CODE_FAST)
  #undef RTE_START_SEC_CODE_FAST
  #error "RTE does not support RTE_START_SEC_CODE_FAST memory section"

#elif defined (RTE_STOP_SEC_CODE_FAST)
  #undef RTE_STOP_SEC_CODE_FAST
  #error "RTE does not support RTE_STOP_SEC_CODE_FAST memory section"

#elif defined (RTE_START_SEC_CODE_SLOW)
  #undef RTE_START_SEC_CODE_SLOW
  #error "RTE does not support RTE_START_SEC_CODE_SLOW memory section"

#elif defined (RTE_STOP_SEC_CODE_SLOW)
  #undef RTE_STOP_SEC_CODE_SLOW
  #error "RTE does not support RTE_STOP_SEC_CODE_SLOW memory section"

#elif defined (RTE_START_SEC_CODE_LIB)
  #undef RTE_START_SEC_CODE_LIB
  #error "RTE does not support RTE_START_SEC_CODE_LIB memory section"

#elif defined (RTE_STOP_SEC_CODE_LIB)
  #undef RTE_STOP_SEC_CODE_LIB
  #error "RTE does not support RTE_STOP_SEC_CODE_LIB memory section"

#else
  #define SECTION_NOT_FOUND

#endif

/*******************************************************************************
**                         Memory Map Class                                   **
*******************************************************************************/

#endif

/*******************************************************************************
* PRE-JUSTIFICATION END SECTION (MISRA-C RULE CHECKER)
*******************************************************************************/
/*
  polyspace:end<MISRA-C:19.1:Not a defect:Justify with annotations> No Impact of this rule violation (AUTOSAR Standard : Memory Mapping)
  polyspace:end<MISRA-C:19.4:Not a defect:Justify with annotations> No Impact of this rule violation (AUTOSAR Standard : Rte SWS #1154, #6713)
  polyspace:end<MISRA-C:19.6:Not a defect:Justify with annotations> No Impact of this rule violation (AUTOSAR Standard : Memory Mapping)
  polyspace:end<MISRA-C:19.7:Not a defect:Justify with annotations> No Impact of this rule violation (AUTOSAR Standard : Rte SWS #1236)
*/

/*******************************************************************************
**                      End of File                                           **
*******************************************************************************/

